language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t phoenix202100/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true phoenix202100/docker-react npm run test
